name: ITBWN
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26.4
  - pytorch=2.8.0
  - torchvision=0.23.0
  - ipykernel
  - matplotlib
  - gdown
  - rich
  - torchinfo
  - torchview